[![Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://www.kaggle.com/code/maryrobynbernabe/kulintang-3-train-test-split-csv)

# Loading Dataset

## Set the dataset path

In [1]:
import os

# This will list every file in the input directory
for root, dirs, files in os.walk('/kaggle/input'):
    for file in files:
        print(os.path.join(root, file))

/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/__results__.html
/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/__notebook__.ipynb
/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/__output__.json
/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/featurizedaudio.csv
/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/custom.css

In [2]:
# define the paths
MAIN_CSV ='/kaggle/input/notebooks/maryrobynbernabe/kulintang-2-audio-extraction-and-featurization/featurizedaudio.csv'

## Import dataset as a dataframe

In [3]:
import pandas as pd

try:
    df = pd.read_csv(MAIN_CSV)
    print("Success! Data shape:", df.shape)
except FileNotFoundError:
    print("Still not finding it. Double-check the path using the os.walk script above.")

Success! Data shape: (1081, 27)

In [4]:
import pandas as pd

# load the main csv
df_main = pd.read_csv(MAIN_CSV)
df_main.head()

,video_segment_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,label
0,IMG_0037_part5.mov,0.110914,636.822926,730.140212,704.956055,0.042457,-388.79868,127.76952,30.357569,0.964475,...,-9.094933,2.113101,9.804668,13.554678,10.162496,5.915236,7.076755,9.991294,4.527101,2
1,IMG_0037_part6.mov,0.105051,802.982334,848.353061,964.883256,0.048331,-370.88208,147.86390,10.282375,-6.605200,...,-0.436702,17.252120,17.207047,9.353372,2.422301,2.440642,4.783227,-7.288693,-19.787868,3
2,IMG_0037_part7.mov,0.117851,824.580504,817.884068,992.065430,0.050767,-356.94830,154.97551,5.095808,-17.982310,...,11.097885,14.794455,7.392744,-1.549907,-4.859143,-3.377399,-8.645940,-23.538470,-19.215622,4
3,IMG_0037_part8.mov,0.070839,1288.281722,1206.854531,1982.711088,0.076848,-268.32053,161.85448,-57.438450,-28.290650,...,14.017271,-4.714745,-6.482290,1.976947,-0.569431,-14.925186,-21.212166,-12.418090,-4.545398,5
4,IMG_0037_part12.mov,0.098182,1416.618909,981.970283,1715.254211,0.091492,-315.66107,115.52594,-67.717110,-48.924007,...,-9.691249,7.581002,0.971637,0.144251,6.229625,-5.574753,-19.128342,-13.515327,9.690474,8

## Set the label column

In [5]:
LABEL_COLUMN = 'label'

## Checking label distribution

In [6]:
# Check the distribution of unique elements in Label  Column
df_main = df_main[df_main[LABEL_COLUMN] != 'n']
df_main = df_main[df_main[LABEL_COLUMN] != '9']
print(df_main[LABEL_COLUMN].value_counts())

label
1    173
4    156
2    155
6    142
3    141
5    108
7    107
8     97
Name: count, dtype: int64

## Split the dataset into train and test

In [7]:
from sklearn.model_selection import train_test_split

# Split the main dataframe to train and test
df_train, df_test = train_test_split(df_main, test_size = 0.2, stratify=df_main[LABEL_COLUMN],random_state=42)

## Reset index of the training data

In [8]:
# Reset the indexes
df_train.reset_index(drop=True)

,video_segment_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,label
0,IMG_0019_part3.mov,0.053615,980.746802,1205.396792,1647.290039,0.038361,-350.16610,170.34305,-15.772644,-2.819955,...,6.490541,-6.668625,-4.746032,3.299501,17.251945,25.107609,10.315108,-8.479652,1.997067,2
1,IMG_0174_part1.mov,0.116304,879.853909,907.530374,1190.559468,0.053711,-336.00040,155.57115,-8.414290,-17.730108,...,16.356054,15.674457,4.344575,17.616684,15.273186,-7.249934,-13.276100,-11.321980,-16.550156,1
2,IMG_0051_part1.mov,0.066470,952.903131,930.097034,1587.304688,0.053339,-323.26767,184.88742,-36.271830,-8.093708,...,-18.575972,-0.291267,2.439108,12.327736,17.080530,0.271001,-2.413107,10.664091,15.423488,1
3,IMG_0100_part7.mov,0.079879,924.663745,820.118237,1249.862007,0.075025,-335.73923,170.05788,-12.482840,-23.212070,...,-8.513394,-5.076893,-6.441819,-16.883305,-9.719841,10.315385,11.480839,3.767828,8.773791,5
4,IMG_0117_part12.mov,0.123468,1314.492471,883.630961,1525.492859,0.094604,-329.36194,129.69724,-51.333427,-40.849113,...,1.793571,13.920622,8.045855,5.544958,-3.796579,-14.444036,-6.756819,-3.773444,8.365838,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
858,IMG_0115_part10.mov,0.108301,1189.433724,762.382369,1313.525391,0.097545,-352.27737,131.70444,-31.566229,-38.562520,...,3.424979,10.055859,3.064452,5.377573,-2.757723,-15.654139,-11.622230,-4.069893,8.777142,8
859,IMG_0140_part3.mov,0.112854,785.809570,942.559609,836.430359,0.052185,-347.89142,165.62546,17.464874,-4.727789,...,20.257570,22.730759,2.375691,-5.397417,-4.403337,-4.508367,-10.451476,-13.649750,-6.386216,3
860,IMG_0049_part7.mov,0.107449,1181.117694,1035.516817,1422.019606,0.074519,-309.40347,150.22348,-43.099236,-31.909636,...,-20.285366,-13.398840,1.079432,-1.119525,6.891990,12.978936,3.440178,-6.487095,-8.460208,7
861,IMG_0219_part7.mov,0.068951,1485.598567,1443.213802,2717.893982,0.084564,-308.36752,118.57230,-52.005253,-11.160712,...,-24.902588,-7.597266,9.470142,-7.215879,7.009657,19.722866,-0.335772,-3.956462,-3.467159,6
862,IMG_0028_part1.mov,0.071885,579.850771,842.202851,696.093750,0.032785,-415.56390,158.48799,29.712840,0.415598,...,-7.072489,-7.493285,-6.087771,-0.188093,4.796153,-0.124060,2.131477,9.242539,11.610799,1

## Check the label distribution of the training data

In [9]:
# Check the distribution of unique elements in Label  Column
print(df_train[LABEL_COLUMN].value_counts())

label
1    138
4    125
2    124
6    113
3    113
5     86
7     86
8     78
Name: count, dtype: int64

## Reset the index of the test data

In [10]:
df_test.reset_index(drop=True)

,video_segment_name,RMSE,SPECTRAL_CENTROID,SPECTRAL_BANDWIDTH,ROLLOFF,ZERO_CROSSING_RATE,MFCC_FEATURE_0,MFCC_FEATURE_1,MFCC_FEATURE_2,MFCC_FEATURE_3,...,MFCC_FEATURE_11,MFCC_FEATURE_12,MFCC_FEATURE_13,MFCC_FEATURE_14,MFCC_FEATURE_15,MFCC_FEATURE_16,MFCC_FEATURE_17,MFCC_FEATURE_18,MFCC_FEATURE_19,label
0,IMG_0079_part4.mov,0.074279,824.784218,742.036387,1146.643066,0.052321,-360.80756,180.964570,-5.716828,-27.921083,...,21.713823,19.980824,1.300567,2.111620,4.443696,3.829234,-7.244342,-19.688082,-8.291594,4
1,IMG_0092_part5.mov,0.096206,1058.691700,763.509071,1398.415903,0.068585,-349.24020,145.001890,-20.154152,-44.954792,...,3.558468,-1.061922,-4.151087,-18.858686,-17.484415,6.751639,18.643690,12.777710,13.444060,5
2,IMG_0113_part2.mov,0.082792,833.775182,837.783913,1340.185547,0.050107,-365.67830,165.891040,-10.313600,-26.896162,...,-4.357621,23.699467,14.519338,1.636591,7.823964,18.715128,18.430424,2.228519,-4.265099,2
3,IMG_0026_part2.mov,0.116547,829.970077,939.317160,1399.244103,0.040077,-320.75745,165.961930,9.296667,-26.853132,...,10.488697,-7.528155,-6.091860,9.044275,22.409372,24.324890,6.841595,-5.165628,5.904742,2
4,IMG_0212_part1.mov,0.072301,1143.334685,1439.072667,2084.900296,0.050041,-351.37335,126.804726,-18.521122,4.040197,...,18.018242,12.914463,10.952389,6.540925,2.893174,3.431541,-7.017755,-10.989840,-2.744940,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,IMG_0099_part3.mov,0.059158,841.004270,689.662093,1063.842773,0.054618,-394.30923,172.849990,-16.945170,-30.918346,...,18.415583,2.986106,1.740148,8.259737,-3.702017,-15.534443,-10.448714,-10.008898,-13.799417,3
212,IMG_0099_part1.mov,0.066264,944.697977,953.758494,1472.953914,0.063383,-359.45510,177.687910,-18.922447,-10.621024,...,19.843130,24.735142,3.396736,6.972595,18.261574,10.213564,-3.805812,-15.725383,-5.311795,1
213,IMG_0025_part3.mov,0.080241,885.152423,1141.874319,1284.814453,0.046322,-359.97180,156.252300,3.628460,-3.146577,...,4.167192,19.147528,13.145452,3.648592,7.545141,19.418250,18.585236,-2.429836,-0.550016,3
214,IMG_0026_part10.mov,0.056624,1408.983073,1198.788874,1498.352051,0.098470,-322.12050,138.080550,-60.206360,-43.361904,...,17.867650,-2.824497,-3.097774,24.299990,21.679451,-3.472568,-8.633465,-13.995429,-3.074943,8
215,IMG_0058_part4.mov,0.048681,1150.266355,1355.369625,1868.288703,0.049111,-299.43220,168.615110,-26.452890,-3.378453,...,-3.559807,7.616370,17.504848,6.786459,-3.668543,-1.262031,6.536061,-6.705519,-13.727420,3

## Check the label distribution of the test data

In [11]:
# Check the distribution of unique elements in Label  Columnp
print(df_test[LABEL_COLUMN].value_counts())

label
1    35
4    31
2    31
6    29
3    28
5    22
7    21
8    19
Name: count, dtype: int64

## Save Training and Test data to csv files

In [12]:
# Save train and test sets to CSV files
df_train.to_csv('train_set.csv', index=False)
df_test.to_csv('test_set.csv', index=False)